#!/usr/bin/env bash
#
# Perform the initial configuration/installs for the system

# cd into dotfiles directory
cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

# import functions
source functions/index.sh

# exit if anything fails
set -e
