# Base match set available everywhere on your machine.
# For a complete introduction, visit [the official docs](https://espanso.org/docs/).

global_vars:
  -
    name: "nowDate"
    params:
      format: "%Y-%m-%d"
    type: "date"
  -
    name: "myName"
    params:
      echo: "Dustin"
    type: "echo"
matches:
  -
    label: "Public IP Address"
    replace: "{{ipAddress}}"
    trigger: ":ip"
    vars:
      - name: "ipAddress"
        params:
          cmd: "curl ifconfig.me"
        type: "shell"
  -
    label: "Sandbox to mess around with."
    replace: "Hello World!"
    triggers:
      - ":sb"
      - ":sandbox"
  -
    label: "Convert from one string case to another."
    replace: "{{convertedCase}}"
    regex: ":c\\((?P<case>.*), (?P<value>.*)\\)"
    vars:
      -
        name: "convertedCase"
        params:
          args:
            - "/opt/homebrew/bin/deno"
            - "run"
            - "%CONFIG%/scripts/convert-case.ts"
            - "{{case}}"
            - "{{value}}"
        type: "script"
